spring.application.name=ecommerce
# MySQL bağlantı bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5434/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Hibernate ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Log levels severity mapping
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN
logging.level.berk.kocaborek=INFO

jwt.secret=${JWT_SECRET}
jwt.expirationMs=3600000
# OpenAPI endpoint ayarı



server.port=8080
# OpenAPI endpoint ayarı
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Eğer Angular localhost'tan gelecekse:
app.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200,http://[::1]:4200


stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
ai.service.url=http://localhost:8000
analytics.internal.api-key=${ANALYTICS_INTERNAL_API_KEY}
stripe.success.url=${STRIPE_SUCCESS_URL:http://localhost:4200/checkout?payment=success}
stripe.cancel.url=${STRIPE_CANCEL_URL:http://localhost:4200/checkout?payment=cancel}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}
