package berk.kocaborek.ecommerce.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.expression.Expression;
import net.sf.jsqlparser.expression.ExpressionVisitorAdapter;
import net.sf.jsqlparser.expression.operators.conditional.OrExpression;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.schema.Column;
import net.sf.jsqlparser.schema.Table;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.select.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.regex.Pattern;

@Service
@RequiredArgsConstructor
@Slf4j
public class AnalyticsService {

    private static final Pattern COMMENT_PATTERN = Pattern.compile("(/\\*.*?\\*/)|(--\\s)|(#)", Pattern.DOTALL);
    private static final Set<String> PUBLIC_CATALOG_TABLES = Set.of(
            "products",
            "categories"
    );
    private static final Set<String> PUBLIC_REVIEW_ANALYTICS_TABLES = Set.of(
            "products",
            "reviews"
    );
    private static final Set<String> SENSITIVE_COLUMNS = Set.of(
            "password",
            "password_hash",
            "api_key",
            "secret",
            "internal_cost",
            "supplier_margin"
    );

    private final JdbcTemplate jdbcTemplate;

    /**
     * Executes a dynamic SQL query generated by the AI Chatbot.
     * Uses JSqlParser to validate AST tree for row-level permissions and safety.
     *
     * @param sql The SQL query to execute.
     */
    public List<Map<String, Object>> executeDynamicQuery(String sql, Long userId, String userRole) {
        if (sql == null || sql.trim().isEmpty()) {
            throw new IllegalArgumentException("SQL query cannot be empty");
        }

        String trimmedSql = sql.trim();
        if (trimmedSql.contains(";") || COMMENT_PATTERN.matcher(trimmedSql).find()) {
            log.error("Blocked potentially multi-statement or commented SQL: {}", sql);
            throw new SecurityException("Comments and multi-statement SQL are prohibited.");
        }

        // 1. Ast SQL Parsing (AV-03, AV-11)
        Statement statement;
        try {
            statement = CCJSqlParserUtil.parse(trimmedSql);
        } catch (JSQLParserException e) {
            log.error("Failed to parse SQL: {}", sql);
            throw new SecurityException("Invalid SQL syntax or unsafe operations detected.");
        }

        // Must be a SELECT statement exactly (No INSERT, UPDATE, DROP, UNION etc)
        if (!(statement instanceof Select)) {
            throw new SecurityException("Only pure SELECT queries are allowed for analytics.");
        }
        
        Select select = (Select) statement;
        if (select.getSelectBody() instanceof SetOperationList) {
            throw new SecurityException("UNION and other set operations are prohibited.");
        }
        if (!(select.getSelectBody() instanceof PlainSelect)) {
            throw new SecurityException("Only simple SELECT statements are allowed.");
        }

        PlainSelect plainSelect = (PlainSelect) select.getSelectBody();

        // 2. Column-Level Restrictions (AV-12)
        if (plainSelect.getSelectItems() != null) {
            for (SelectItem item : plainSelect.getSelectItems()) {
                if (item instanceof AllColumns || item instanceof AllTableColumns) {
                    throw new SecurityException("SELECT * is not allowed for analytics queries.");
                }
                
                item.accept(new SelectItemVisitorAdapter() {
                    @Override
                    public void visit(SelectExpressionItem item) {
                        item.getExpression().accept(new ExpressionVisitorAdapter() {
                            @Override
                            public void visit(Column column) {
                                String colName = column.getColumnName().toLowerCase(Locale.ROOT);
                                if (SENSITIVE_COLUMNS.contains(colName)) {
                                    throw new SecurityException("Sensitive columns (" + colName + ") are not accessible.");
                                }
                            }
                        });
                    }
                });
            }
        }

        // 3. Row-Level Ownership Restrictions (AV-02, AV-05, AV-09)
        if (userRole != null && !userRole.equalsIgnoreCase("ADMIN") && userId != null) {
             validateOwnershipCondition(plainSelect, userId, userRole);
        }

        log.info("Executing AI-generated SQL query: {}", sql);
        
        try {
            return jdbcTemplate.queryForList(sql);
        } catch (Exception e) {
            log.error("Error executing dynamic SQL: {}", e.getMessage());
            throw new RuntimeException("Database execution error: " + e.getMessage());
        }
    }

    private void validateOwnershipCondition(PlainSelect plainSelect, Long userId, String userRole) {
        if (isPublicCatalogQuery(plainSelect) && userRole != null && userRole.equalsIgnoreCase("CUSTOMER")) {
            return;
        }

        if (isPublicReviewAnalyticsQuery(plainSelect) && userRole != null && userRole.equalsIgnoreCase("CUSTOMER")) {
            return;
        }

        // Enforce that an ID-based WHERE clause exists for the primary table or joins
        Expression where = plainSelect.getWhere();
        if (where == null) {
            throw new SecurityException("Missing mandatory ownership WHERE clause for non-admin user.");
        }

        AtomicBoolean hasOrExpression = new AtomicBoolean(false);
        AtomicBoolean hasCorrectUserId = new AtomicBoolean(false);

        where.accept(new ExpressionVisitorAdapter() {
            @Override
            public void visit(OrExpression expr) {
                hasOrExpression.set(true); // Malicious OR 1=1 bypass check
                super.visit(expr);
            }

            @Override
            public void visit(net.sf.jsqlparser.expression.LongValue expr) {
                if (expr.getValue() == userId) {
                    hasCorrectUserId.set(true);
                }
                super.visit(expr);
            }
            
            // Double values can sometimes parse as ID wrappers depending on backend formatting
            @Override
            public void visit(net.sf.jsqlparser.expression.DoubleValue expr) {
                 if (expr.getValue() == (double) userId) {
                    hasCorrectUserId.set(true);
                }
                super.visit(expr);
            }
        });

        if (hasOrExpression.get()) {
            throw new SecurityException("OR expressions are prohibited in user queries to prevent bypass.");
        }
        
        if (!hasCorrectUserId.get()) {
            throw new SecurityException("Unauthorized query: You can only query data matching your own user ID.");
        }
    }

    private boolean isPublicCatalogQuery(PlainSelect plainSelect) {
        Set<String> tableNames = new HashSet<>();
        collectTableName(plainSelect.getFromItem(), tableNames);

        if (plainSelect.getJoins() != null) {
            for (Join join : plainSelect.getJoins()) {
                collectTableName(join.getRightItem(), tableNames);
            }
        }

        return !tableNames.isEmpty() && tableNames.stream().allMatch(PUBLIC_CATALOG_TABLES::contains);
    }

    private boolean isPublicReviewAnalyticsQuery(PlainSelect plainSelect) {
        Set<String> tableNames = new HashSet<>();
        collectTableName(plainSelect.getFromItem(), tableNames);

        if (plainSelect.getJoins() != null) {
            for (Join join : plainSelect.getJoins()) {
                collectTableName(join.getRightItem(), tableNames);
            }
        }

        if (!tableNames.equals(PUBLIC_REVIEW_ANALYTICS_TABLES)) {
            return false;
        }

        if (plainSelect.getGroupBy() == null) {
            return false;
        }

        boolean hasCountAggregate = false;
        if (plainSelect.getSelectItems() != null) {
            for (SelectItem item : plainSelect.getSelectItems()) {
                String itemSql = item.toString().toLowerCase(Locale.ROOT);
                if (itemSql.contains("reviews.user_id") || itemSql.contains("reviews.comment")
                        || itemSql.contains("reviews.sentiment") || itemSql.contains("reviews.star_rating")) {
                    return false;
                }
                if (itemSql.contains("count(")) {
                    hasCountAggregate = true;
                }
            }
        }

        if (plainSelect.getWhere() != null) {
            String whereSql = plainSelect.getWhere().toString().toLowerCase(Locale.ROOT);
            if (whereSql.contains("reviews.user_id") || whereSql.contains("reviews.comment")
                    || whereSql.contains("reviews.sentiment") || whereSql.contains("reviews.star_rating")) {
                return false;
            }
        }

        return hasCountAggregate;
    }

    private void collectTableName(FromItem fromItem, Set<String> tableNames) {
        if (fromItem instanceof Table table && table.getName() != null) {
            tableNames.add(table.getName().toLowerCase(Locale.ROOT));
        }
    }
}
